# Generated by Django 3.1.7 on 2021-03-20 05:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('price', models.FloatField()),
                ('description', models.TextField(blank=True, max_length=300)),
                ('created_at', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('num_pages', models.IntegerField(default=1)),
                ('genre', models.CharField(choices=[('NotDefined', 'Not Defined'), ('Horror', 'Horror'), ('Comedy', 'Comedy')], default='NotDefined', max_length=10)),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
    ]
