# Generated by Django 3.1.7 on 2021-03-20 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('price', models.FloatField()),
                ('description', models.TextField(blank=True, max_length=300)),
                ('created_at', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('Bullet', 'Bullet'), ('Food', 'Food'), ('Travel', 'Travel'), ('Sport', 'Sport')], max_length=10)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal',
                'verbose_name_plural': 'Journals',
            },
        ),
    ]
